### ISSUE TITLE
Project incomplete

### ISSUE THREAD

**Issue by aliceyixin** [CVxTz/COLA_pytorch#1]
Hi Mansar,

May I ask you some questions about the code “prepare_data.py”?
It's not in the folder "audio_encoder" you wrote in README.
And it lacks the argument "mp3_path ".
Does that mean this repo is incomplete?

BTW, your blogs and implementations are very impressive! Well done : )

Cordialement,
Alice

**Comment by CVxTz** [comment]
Hello,

Thank you for your comment.
I just fixed the correct path of prepare_data to `python supervised_examples/prepare_data.py --metadata_path "/media/ml/data_ml/fma_metadata/" `
It does not need the path to mp3_path, instead in needs the argument to metadata_path. 
--metadata_path is the path to where you de-zipped the result of `wget -c https://os.unil.cloud.switch.ch/fma/fma_metadata.zip`

Best,

Youness
