### ISSUE TITLE
Bilinear similarity has no weights

### ISSUE THREAD

**Issue by turian** [CVxTz/COLA_pytorch#2]
You compute the similarity like this:

```
         y_hat = torch.mm(x1, x2.t())
```

However, the original paper suggests there should be a learned weight matrix W for the bilnear transform:

![image](https://user-images.githubusercontent.com/65918/102206190-81640b80-3ecc-11eb-90af-540910692e53.png)

**Comment by CVxTz** [comment]
Hello,
The W is applied in the def **forward** : 
`        x1 = self.linear(x1)

        return x1, x2
`
with:
`self.linear = torch.nn.Linear(512, 512, bias=False)`

**Comment by turian** [comment]
Oh I see, that is very nice.
